# Permalinks
permalink: pretty

pages_list: {'JavaAlgorithms':'https://github.com/VVMajor/JavaAlgorithms','WP Workbench':'http://wp.vvmajor.tk/','About':'/about','Contact':'/contact'}
pages_list_future: {'Archive':'/archive','Feed':'/atom.xml'}

copyString: "&copy; VVMajor"
copyDate: "2015"