# Permalinks
permalink: pretty

pages_list: {'JavaAlgorithms':'https://github.com/VVMajor/JavaAlgorithms','CmdLinkStatus':'https://github.com/VVMajor/VVMAJOR_CmdLinkStatus/blob/master/VVMAJORLinkStatus.cmd','WP Workbench':'http://wp.vvmajor.tk/','About Author':'/about','Contact':'/contact'}
pages_list_future: {'Archive':'/archive','Feed':'/atom.xml'}

copyString: "&copy; VVMajor"
copyDate: "2015"